"""MJCF model generators for the twin-fidelity harness.

Both models are written out to models/*.xml as plain, readable files (not
hidden inside a temp string) so a reader can inspect exactly what was
simulated without re-running Python.
"""

from __future__ import annotations

import math

from . import analytical

INCLINE_THETA_DEG = 30.0
INCLINE_MU = 0.15  # must be < tan(30deg) = 0.577 for case 1 (MATCH case: sliding)
INCLINE_MASS = 1.0
INCLINE_RADIUS = 0.05  # sphere radius (m) -- see note in incline_xml on why a
# sphere, not a box, is used as the sliding "block"

BALL_MASS = 0.5
BALL_RADIUS = 0.1
BALL_DROP_HEIGHT = 1.0  # h_0, ball-center height above the resting contact point (m)
BALL_E_TARGET = 0.75
CONTACT_FREQ_HZ = 120.0  # natural frequency of the virtual spring-dashpot contact
GEOM_SOLIMP = "0.998 0.9999 0.0002 0.5 2"  # near-constant impedance (see DECISION.md)


def incline_xml(theta_deg: float = INCLINE_THETA_DEG, mu: float = INCLINE_MU) -> str:
    theta_rad = math.radians(theta_deg)
    # sanity check at generation time -- fail loudly if this stops being a
    # sliding (MATCH) case.
    if mu >= math.tan(theta_rad):
        raise ValueError("incline_xml: mu >= tan(theta), not a sliding case")

    # The plane passes through the world origin. Start the sphere a small
    # gap above the (rotated) plane along its normal direction -- which,
    # since the body carries the SAME rotation as the plane, is exactly its
    # own local +Z axis. World offset = R_y(theta) @ (0, 0, radius + gap).
    r = INCLINE_RADIUS
    gap = 0.01
    body_x = (r + gap) * math.sin(theta_rad)
    body_z = (r + gap) * math.cos(theta_rad)

    return f"""<mujoco model="incline">
  <!-- Case 1: block sliding down a frictional incline, theta={theta_deg} deg,
       mu={mu} (tan(theta)={math.tan(theta_rad):.4f}, so mu < tan(theta):
       kinetic sliding, not static). Generated by harness/models.py -- do not
       hand-edit; re-run `python -m harness.models` instead.

       The "block" is a SPHERE (single contact point -- a flush BOX makes 4
       exactly-coplanar corner contacts, a degenerate/statically-
       indeterminate configuration: empirically each corner independently
       reported close to the FULL body weight as its own normal force
       [~4x m*g*cos(theta) summed], which then let friction, bounded per
       CONTACT by mu*normal_at_that_contact, resist far more than
       mu*m*g*cos(theta) in aggregate -- the block stuck to the plane).

       The body carries TWO slide joints (a compound joint, no rotation):
       one along local +X (down-slope -- because the body is rotated by
       theta, this is the DOF we measure) and one along local +Z (the
       contact normal direction). The normal-direction joint is what makes
       this a physically well-posed friction test: it gives the contact
       solver an actual degree of freedom to equilibrate the normal force
       against (N settles to m*g*cos(theta) through genuine dynamics), and
       it comes with a small critical-ish damping purely to settle the
       initial drop-and-touch transient quickly. A first attempt used only
       the down-slope joint (rotation AND normal motion welded away); with
       no normal DOF, MuJoCo's contact Jacobian for the normal direction is
       identically zero with respect to the one remaining DOF, so the
       solver has no dynamical requirement to converge on any particular
       normal force at all -- it settled on an under-determined, physically
       meaningless value. Both a rotation-free box and a rotation-free
       sphere-with-only-one-DOF are traps; sphere + 2 orthogonal slide
       joints is the configuration that is simultaneously non-degenerate
       (one contact point) and dynamically well-posed (N is a real
       equilibrium, not a solver artifact), while still excluding
       spin/rolling so the measured quantity matches the closed form's
       pure-translation assumption. -->
  <compiler angle="degree"/>
  <option timestep="0.001" integrator="implicitfast" cone="elliptic"/>
  <default>
    <geom friction="{mu} 0.005 0.0001"/>
  </default>
  <worldbody>
    <light directional="true" diffuse="0.8 0.8 0.8" pos="0 0 5" dir="0 0 -1"/>
    <geom name="incline_surface" type="plane" size="5 5 0.1" euler="0 {theta_deg} 0"/>
    <body name="block" pos="{body_x:.6f} 0 {body_z:.6f}" euler="0 {theta_deg} 0">
      <joint name="slide_down" type="slide" axis="1 0 0" damping="0"/>
      <joint name="slide_normal" type="slide" axis="0 0 1" damping="2.0"/>
      <geom name="block_geom" type="sphere" size="{r}" mass="{INCLINE_MASS}"/>
    </body>
  </worldbody>
</mujoco>
"""


def bounce_xml(
    e_target: float = BALL_E_TARGET,
    h0: float = BALL_DROP_HEIGHT,
    mass: float = BALL_MASS,
    radius: float = BALL_RADIUS,
    contact_freq_hz: float = CONTACT_FREQ_HZ,
) -> str:
    stiffness, damping = analytical.solref_direct_for_target(e_target, mass, contact_freq_hz)
    zeta = analytical.damping_ratio_for_restitution(e_target)

    return f"""<mujoco model="bounce">
  <!-- Case 2: ball dropped from rest at height h0={h0} (center height above
       the resting/contact position, i.e. above z={radius}) onto a fixed
       plane. Generated by harness/models.py -- do not hand-edit; re-run
       `python -m harness.models` instead.

       MuJoCo has no first-class restitution knob (verified against the
       installed MuJoCo {_mujoco_version()} MjModel field list -- no
       elasticity/bounce/restitution field exists for rigid contacts; see
       DECISION.md). This uses the "direct" solref format
       (-stiffness, -damping), which MuJoCo's own docs recommend for
       restitution work ("allowing for perfectly elastic collisions...
       recommended format for system identification" -- doc/modeling.rst).

       stiffness/damping below are DERIVED (harness/analytical.py
       solref_direct_for_target) from a target e={e_target} via the
       standard damped-harmonic-oscillator restitution formula
       e = exp(-zeta*pi/sqrt(1-zeta^2)), giving zeta={zeta:.6f},
       contact natural frequency={contact_freq_hz} Hz ->
       stiffness={-stiffness:.4f} N/m, damping={-damping:.4f} N*s/m.

       This is a HEURISTIC TARGET, not a guaranteed outcome -- run.py
       measures the actual effective restitution from the simulated bounce
       heights and reports the (expected) deviation. -->
  <compiler angle="degree"/>
  <option timestep="0.0002" integrator="implicitfast" cone="elliptic"/>
  <default>
    <geom solref="{stiffness:.6f} {damping:.6f}" solimp="{GEOM_SOLIMP}" friction="0 0 0"/>
  </default>
  <worldbody>
    <light directional="true" diffuse="0.8 0.8 0.8" pos="0 0 5" dir="0 0 -1"/>
    <geom name="ground" type="plane" size="5 5 0.1"/>
    <body name="ball" pos="0 0 {radius + h0}">
      <freejoint name="ball_free"/>
      <geom name="ball_geom" type="sphere" size="{radius}" mass="{mass}"/>
    </body>
  </worldbody>
</mujoco>
"""


def _mujoco_version() -> str:
    import mujoco

    v = mujoco.__version__
    return v


def write_models(models_dir: str = "models") -> None:
    import os

    os.makedirs(models_dir, exist_ok=True)
    with open(os.path.join(models_dir, "incline.xml"), "w") as f:
        f.write(incline_xml())
    with open(os.path.join(models_dir, "bounce.xml"), "w") as f:
        f.write(bounce_xml())


if __name__ == "__main__":
    write_models()
    print("wrote models/incline.xml and models/bounce.xml")
